```{r}
library (readr)
library(paletteer)
library(ggrepel)
urlfile="https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv"

nytdata <- read_csv(url(urlfile))
```

```{r}
nyt_curve <- nytdata %>%
  select(date, state, cases, deaths) %>%
  group_by(state) %>%
  arrange(date) %>%
  mutate(cu_cases = cumsum(cases), 
         cu_deaths = cumsum(deaths)) %>%
  filter(cu_cases > 99) %>%
  mutate(days_elapsed = date - min(date),
          end_label = ifelse(date == max(date), state, NA))

nyt_curve
```

```{r}
focus_st <- c("Washington", "California", "Texas", "Michigan", "New York", "Louisiana", "New Jersey")

## Colors
state_cols <- c(prismatic::clr_darken(paletteer_d("ggsci::category20_d3"), 0.2)[1:length(focus_st)], "gray70")
```


```{r}
us_case <- nyt_curve %>%
  mutate(end_label = case_when(state %in% focus_st ~ end_label,
                               TRUE ~ NA_character_), 
         cgroup = case_when(state %in% focus_st ~ state, 
                            TRUE ~ "ZZOTHER")) %>%
  ggplot(mapping = aes(x = days_elapsed, y = cu_cases, 
         color = cgroup, label = end_label, 
         group = state)) + 
  geom_line(size = 0.8) + 
  geom_text_repel(nudge_x = -1.1,
                  nudge_y = 0.4,
                  segment.color = NA,
                  size = 3,
                  family="ITC Officina Sans LT Bold") + 
  guides(color = FALSE) + 
  #theme_minimal() +
theme_delabj()+
  scale_color_manual(values = state_cols) +
  #ggthemes::scale_color_economist() +
  scale_y_continuous(position = "right",
                    labels = scales::comma_format(accuracy = 1), 
                     breaks = 2^seq(0, 30),
                      #breaks = c(0, 9000),
                    #limits=c(0, 9000),
                     trans = "log2") + 
  scale_x_continuous(breaks=seq(0, 60, 10)) +
  labs(x = "\nNumber of days since 100th case \n", 
       y = "", 
       title = "Confirmed covid-19 cases", 
       #subtitle = paste("Data as of", format(max(cov_curve$date), "%A, %B %e, %Y \n")), 
       subtitle = "Log scale",
        caption = "Source: New York Times; Data updated 14 April, 2020\nwww.fishwongy.com") +
         #"Data: https://www.ecdc.europa.eu/ \nwww.fishwongy.com") +
   theme(#legend.position="top",
        text = element_text(size = 12, family="ITC Officina Sans LT Book"),
        #axis.line = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.caption.position = "plot",
        plot.title = element_text(size = 15, hjust =  0,face = "bold", family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_text(hjust = 0.95, color = "gray30", family="ITC Officina Sans LT Book"),
        plot.caption = element_text(hjust = 0, size = 12, family="ITC Officina Sans LT Book")) 
```

```{r}
nyt <- nyt_curve %>%
  mutate(end_label = case_when(state %in% focus_st ~ end_label,
                               TRUE ~ NA_character_), 
         cgroup = case_when(state %in% focus_st ~ state, 
                            TRUE ~ "ZZOTHER")) %>%
  ggplot(mapping = aes(x = days_elapsed, y = cu_cases, 
         color = cgroup, label = end_label, 
         group = state)) + 
  geom_line(size = 1.3) + 
  geom_text_repel(nudge_x = 1.1,
                  nudge_y = 0,
                  segment.color = NA,
                  size = 6,
                  family="ITC Officina Sans LT Bold") + 
  guides(color = FALSE) + 
  theme_minimal() +
  #theme_economist() +
  scale_color_manual(values = state_cols) +
  #ggthemes::scale_color_economist() +
  scale_y_continuous(position = "right",
                    labels = scales::comma_format(accuracy = 1), 
                     breaks = 2^seq(0, 30),
                      #breaks = c(0, 9000),
                    #limits=c(0, 9000),
                     trans = "log2") + 
  scale_x_continuous(breaks=seq(0, 60, 10)) +
  labs(x = "\nNumber of days since 100th case \n", 
       y = "", 
       title = "States' rates", 
       #subtitle = paste("Data as of", format(max(cov_curve$date), "%A, %B %e, %Y \n")), 
       subtitle = "Confirmed covid-19 cases\nLog scale",
        caption = "Source: New York Times; Data updated 8 April, 2020\nwww.fishwongy.com") +
         #"Data: https://www.ecdc.europa.eu/ \nwww.fishwongy.com") +
   theme(#legend.position="top",
        text = element_text(size = 15, family="ITC Officina Sans LT Book"),
        #axis.line = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        
        plot.title = element_text(size = 18, hjust =  0,face = "bold", family="ITC Officina Sans LT Bold"),
        #plot.subtitle = element_text(hjust = 1.06, color = "gray30", family="ITC Officina Sans LT Book"),
        plot.caption = element_text(hjust = 0, size = 11, family="ITC Officina Sans LT Book")) 

ggsave("US_case(14 Apr).png", 
       nyt, width = 11, height = 12, dpi = 300)
```


#Death
```{r}
nyt_death <- nytdata %>%
  select(date, state, cases, deaths) %>%
  group_by(state) %>%
  arrange(date) %>%
  mutate(cu_cases = cumsum(cases), 
         cu_deaths = cumsum(deaths)) %>%
  filter(cu_deaths > 9) %>%
  mutate(days_elapsed = date - min(date),
          end_label = ifelse(date == max(date), state, NA))

nyt_death
```

```{r}
us_death <- nyt_death %>%
  mutate(end_label = case_when(state %in% focus_st ~ end_label,
                               TRUE ~ NA_character_), 
         cgroup = case_when(state %in% focus_st ~ state, 
                            TRUE ~ "ZZOTHER")) %>%
  ggplot(mapping = aes(x = days_elapsed, y = cu_deaths, 
         color = cgroup, label = end_label, 
         group = state)) + 
  geom_line(size = 0.8) + 
  geom_text_repel(nudge_x = -1.1,
                  nudge_y = 0.4,
                  segment.color = NA,
                  size = 3,
                  family="ITC Officina Sans LT Bold") + 
  guides(color = FALSE) + 
  #theme_minimal() +
  theme_delabj() +
  scale_color_manual(values = state_cols) +
  #ggthemes::scale_color_economist() +
  scale_y_continuous(position = "right",
                    labels = scales::comma_format(accuracy = 1), 
                     breaks = 2^seq(0, 20),
                      #breaks = c(0, 9000),
                    #limits=c(0, 9000),
                     trans = "log2") + 
  scale_x_continuous(breaks=seq(0, 60, 10)) +
  labs(x = "\nNumber of days since 10th death \n", 
       y = "", 
      title = "Confirmed covid-19 deaths", 
       subtitle = "Log scale")+
        #caption = "Source: New York Times; Data updated 8 April, 2020\nwww.fishwongy.com") +
         #"Data: https://www.ecdc.europa.eu/ \nwww.fishwongy.com") +
   theme(#legend.position="top",
        text = element_text(size = 12, family="ITC Officina Sans LT Book"),
        #axis.line = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        
        plot.title = element_text(size = 15, hjust =  0, family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_text(hjust = 0.985, color = "gray30", family="ITC Officina Sans LT Book"),
        plot.caption = element_text(hjust = 0, size = 7, family="ITC Officina Sans LT Book")) 
```

```{r}
us_death <- nyt_death %>%
  mutate(end_label = case_when(state %in% focus_st ~ end_label,
                               TRUE ~ NA_character_), 
         cgroup = case_when(state %in% focus_st ~ state, 
                            TRUE ~ "ZZOTHER")) %>%
  ggplot(mapping = aes(x = days_elapsed, y = cu_deaths, 
         color = cgroup, label = end_label, 
         group = state)) + 
  geom_line(size = 1.3) + 
  geom_text_repel(nudge_x = 1.1,
                  nudge_y = 0.2,
                  segment.color = NA,
                  size = 6,
                  family="ITC Officina Sans LT Bold") + 
  guides(color = FALSE) + 
  theme_minimal() +
  #theme_economist() +
  scale_color_manual(values = state_cols) +
  #ggthemes::scale_color_economist() +
  scale_y_continuous(position = "right",
                    labels = scales::comma_format(accuracy = 1), 
                     breaks = 2^seq(0, 20),
                      #breaks = c(0, 9000),
                    #limits=c(0, 9000),
                     trans = "log2") + 
  scale_x_continuous(breaks=seq(0, 60, 10)) +
  labs(x = "\nNumber of days since 10th death \n", 
       y = "", 
       title = "States' rates", 
       #subtitle = paste("Data as of", format(max(cov_curve$date), "%A, %B %e, %Y \n")), 
       subtitle = "Confirmed covid-19 deaths\nLog scale",
        caption = "Source: New York Times; Data updated 8 April, 2020\nwww.fishwongy.com") +
         #"Data: https://www.ecdc.europa.eu/ \nwww.fishwongy.com") +
   theme(#legend.position="top",
        text = element_text(size = 15, family="ITC Officina Sans LT Book"),
        #axis.line = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        
        plot.title = element_text(size = 18, hjust =  0, family="ITC Officina Sans LT Bold"),
        #plot.subtitle = element_text(hjust = 1.06, color = "gray30", family="ITC Officina Sans LT Book"),
        plot.caption = element_text(hjust = 0, size = 11, family="ITC Officina Sans LT Book")) 

ggsave("US_death(14 Apr).png", 
       us_death, width = 11, height = 12, dpi = 300)
```








#Small graph
```{r}
nyt_50 <- nyt_curve %>%
  group_by(state) %>%
  filter(cu_cases == max(cu_cases)) %>%
  ungroup() %>%
  #top_n(50, cu_cases) %>%
  select(state, cu_cases) %>%
  mutate(days_elapsed = 1, 
             cu_cases = max(nyt_curve$cu_cases) - 1e4) 

nyt_50
```

```{r}
nyt_curve_bg <- nyt_curve %>% 
  select(-state) 

nyt_curve_endpoints <- nyt_curve%>% 
  group_by(state) %>%
  filter(cu_cases == max(cu_cases)) %>%
  select(state, days_elapsed, cu_cases) %>%
  ungroup()
```

```{r}
us_50 <- nyt_curve  %>%
  #filter(iso3 %in% top_50$iso3) %>%
  #mutate(cname = recode(cname, `United States` = "USA",
                      #  `Iran, Islamic Republic of` = "Iran", 
                       # `Korea, Republic of` = "South Korea", 
                        #`United Kingdom` = "UK")) %>%
  ggplot(mapping = aes(x = days_elapsed, y = cu_cases)) + 
  theme_delabj() +
  #theme_minimal() +
  # The line traces for every country, in every panel
  geom_line(data = nyt_curve_bg, 
            aes(group = state),
            size = 0.15, color = "gray80") + 
  # The line trace in red, for the country in any given panel
  geom_line(color = "firebrick",
            lineend = "round") + 
  # The point at the end. Bonus trick: some points can have fills!
  geom_point(data = nyt_curve_endpoints, 
             size = 1.1, 
             shape = 21, 
             color = "firebrick",
             fill = "firebrick2"
             ) + 
  # The country label inside the panel, in lieu of the strip label
  geom_text(data = nyt_50, 
             mapping = aes(label = state), 
             vjust = "inward", 
             hjust = "inward",
             fontface = "bold", 
             color = "firebrick", 
             size = 2.1) + 
  # Log transform and friendly labels
  scale_y_log10(labels = scales::label_number_si()) + 
  # Facet by country, order from high to low
  facet_wrap(~ reorder(state, -cu_cases), ncol = 5) + 
  labs(x = "Days Since 100th Confirmed Case", 
       y = "", 
       title = "States' rates", 
         subtitle = "Cumulative Number of Reported Cases of COVID-19: All US States")+ 
       # caption = "Source: New York Times\nwww.fishwongy.com") + 
 theme(text = element_text(size = 12, family="ITC Officina Sans LT Book"),
          plot.title = element_text(size = 21, family="ITC Officina Sans LT Bold"),
          plot.subtitle = element_text(size = 15),
          plot.caption = element_text(hjust = 0, size = rel(1)),
          # turn off the strip label and tighten the panel spacing
          strip.text = element_blank(),
          panel.spacing.x = unit(-0.05, "lines"),
          panel.spacing.y = unit(0.3, "lines"),
          axis.text.y = element_text(size = rel(0.5)),
          axis.title.x = element_text(size = rel(1)),
          axis.title.y = element_text(size = rel(1)),
          axis.text.x = element_text(size = rel(0.5)),
          legend.text = element_text(size = rel(1)))

```

p1 / (p2 | p3)
```{r}
# patchwork
us_50 / (us_case | us_death) +
  plot_annotation(#title = "States' rates", 
                  #subtitle = "How is Covid-19 spreading in the US?",
                  theme = theme(plot.title = element_text(size = 20), 
                                plot.subtitle = element_text(size = 14))) &
  theme(plot.title = element_text(family = "ITC Officina Sans LT Bold"),
    text = element_text("ITC Officina Sans LT Book")) 

+
  ggsave("us_patch.png", dpi = 320, width = 10.8, height = 12)
```






```{r}
us_50 <- nyt_curve  %>%
  #filter(iso3 %in% top_50$iso3) %>%
  #mutate(cname = recode(cname, `United States` = "USA",
                      #  `Iran, Islamic Republic of` = "Iran", 
                       # `Korea, Republic of` = "South Korea", 
                        #`United Kingdom` = "UK")) %>%
  ggplot(mapping = aes(x = days_elapsed, y = cu_cases)) + 
  #theme_economist() +
  theme_minimal() +
  # The line traces for every country, in every panel
  geom_line(data = nyt_curve, 
            aes(group = state),
            size = 0.15, color = "gray80") + 
  # The line trace in red, for the country in any given panel
  geom_line(color = "firebrick",
            lineend = "round") + 
  # The point at the end. Bonus trick: some points can have fills!
  geom_point(data = nyt_curve_endpoints, 
             size = 1.1, 
             shape = 21, 
             color = "firebrick",
             fill = "firebrick2"
             ) + 
  # The country label inside the panel, in lieu of the strip label
  geom_text(data = nyt_50, 
             mapping = aes(label = state), 
             vjust = "inward", 
             hjust = "inward",
             fontface = "bold", 
             color = "firebrick", 
             size = 4) + 
  # Log transform and friendly labels
  scale_y_log10(labels = scales::label_number_si()) + 
  # Facet by country, order from high to low
  facet_wrap(~ reorder(state, -cu_cases), ncol = 5) + 
  labs(x = "Days Since 100th Confirmed Case", 
       y = "", 
       title = "Cumulative Number of Reported Cases of COVID-19: All US States", 
         subtitle = "Data as of 8 April, 2020", 
        caption = "Source: New York Times\nwww.fishwongy.com") + 
 theme(text = element_text(size = 15, family="ITC Officina Sans LT Book"),
          plot.title = element_text(size = 18, family="ITC Officina Sans LT Bold"),
          #plot.subtitle = element_text(size = rel(0.7)),
          plot.caption = element_text(size = 11, hjust = 0),
          # turn off the strip label and tighten the panel spacing
          strip.text = element_blank(),
          panel.spacing.x = unit(-0.05, "lines"),
          panel.spacing.y = unit(0.3, "lines"),
          axis.text.y = element_text(size = rel(0.5)),
          axis.title.x = element_text(size = rel(1)),
          axis.title.y = element_text(size = rel(1)),
          axis.text.x = element_text(size = rel(0.5)),
          legend.text = element_text(size = rel(1)))

ggsave("US50(14 Apr).png", 
       us_50, width = 11, height = 12, dpi = 300)
```
