#Worldwide

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(tidycovid19)
  library(paletteer)
  library(ggplot2)
  library(delabj)
  library(patchwork)
  library(sf)
library(tmap)
#library(dplyr)
})
```

```{r}
covid19_dta <- download_merged_data(silent = TRUE, cached = TRUE)
```

```{r}
world_rnatural <- rnaturalearth::ne_download(returnclass = "sf")
# names(world_iso) # variables available
world_iso <- world_rnatural %>% 
  select(NAME_LONG, ISO_A3_EH, POP_EST, GDP_MD_EST, CONTINENT)

world_projected <- world_iso %>% 
  st_transform("+proj=moll")
```

```{r}
p <- dplyr::left_join(world_projected, covid19_dta, by = c("ISO_A3_EH"= "iso3c"))
p$Area_km <- as.numeric(st_area(p)) / 1e6
p$`Pop/km2` <- as.numeric(p$POP_EST) / p$Area_km 
```

```{r}
p_yesterday <- p %>% 
  filter(date == max(date, na.rm = T) - 1)
plot(p_yesterday)
```

```{r}
colnames(p_yesterday)[8] <- "Confirmed"
colnames(p_yesterday)[9] <- "Deaths"
colnames(p_yesterday)[10] <- "Recovered"
```



```{r}
g <- st_graticule(p_yesterday)
```

```{r}
#Moving the legend:
tm_shape(g) +
  tm_lines(col = "grey", alpha = .3) +
  tm_shape(p_yesterday) +
  tm_polygons(
    c("Deaths", "Recovered"),
    palette = "-viridis",
    style = "log10_pretty"
    ) +
   tm_style("cobalt") +
 # tm_scale_bar(color.dark = "gray60",
  #  position = c("right", "bottom")) + 
  tm_compass(type = "8star", size = 3, fontsize = 0.5, 
    position = c("right", "top")) +
  tm_layout(title = "Covid-19 data",title.size = 0.8,title.fontfamily = "ITC Officina Sans LT Bold", title.position = c("left", "top"),
            legend.position = c(0.01, 0.25),
            fontfamily = "ITC Officina Sans LT Book",
            legend.title.fontfamily = "ITC Officina Sans LT Bold") +
  tm_credits("Data till 26 Apr\nwww.fishwongy.com", position = c("left", "bottom"), size = 0.6) 
  
```

```{r}
tm_shape(g) +
  tm_lines(col = "grey", alpha = 0.4) +
  tm_shape(p_yesterday) +
  tm_polygons() +
  tm_style("cobalt") +
  tm_layout(title = "Covid-19 data",title.size = 0.8,title.fontfamily = "ITC Officina Sans LT Bold", title.position = c("left", "top"),
            legend.position = c(0.01, 0.35),
            fontfamily = "ITC Officina Sans LT Book",
            legend.title.fontfamily = "ITC Officina Sans LT Bold") +
  tm_shape(p_yesterday) +
  tm_fill(col = "#130140") + ##180057
  tm_borders(lwd = 2, col = "#ffe4f2", alpha = 0.2)+
   tm_compass(type = "8star", size = 3, fontsize = 0.5, position = c("right", "top")) +
  tm_dots(
    col = c("#ffe4f2", "#929cb0"),
    size = c("Deaths", "Recovered"),
    palette = "viridis",
    style = "log10_pretty",
    alpha = 0.7
    ) +
  tm_credits("Data till 26 Apr\nwww.fishwongy.com", position=c("left", "bottom"))
```


#USA
```{r}
urlfile="https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv"
nytdata <- read_csv(url(urlfile))
```

```{r}
colnames(nytdata)[4] <- "Confirmed"
colnames(nytdata)[5] <- "Deaths"
```

```{r}
state <- rnaturalearth::ne_states(country = "United States of America", geounit = "United States of America",
  returnclass = c("sf"))

# names(state_iso) # variables available
state_iso <- state %>% 
  select(name, region)
```

#Attribute joins
```{r}
w <- dplyr::left_join(state_iso, nytdata, by = c("name"= "state"))
```

#Plotting international Covid-19 data for a single day
```{r}
w_yesterday <- w %>% 
  filter(date == max(date, na.rm = T) - 1)
plot(w_yesterday)
```

```{r}
b = c(0, 10, 100, 1000, 10000, 100000)
plot(w_yesterday["Deaths"], breaks = b)
```

```{r}
w_yesterday2 <- subset(w_yesterday, ! (name %in% c("Alaska", "Hawaii", "Puerto Rico")))
```

```{r}
b = c(0, 10, 100, 1000, 10000, 100000)
plot(w_yesterday2["Deaths"], breaks = b)
```

```{r}
g <- st_graticule(w_yesterday2)
```

**Making maps with tmap**
```{r}
tm_shape(g) +
  tm_lines(col = "grey", alpha = .3) +
tm_shape(w_yesterday2) +
  tm_polygons(c("Confirmed", "Deaths"),
    palette = "-viridis",
    style = "log10") +
  tm_style("cobalt") +
 tm_layout(title = "Covid-19 data", title.size = 1,title.fontfamily = "ITC Officina Sans LT Bold", title.position = c(0.75, 0.95),
           legend.position = c(0.84, 0.02), #0.01, 0.1
           legend.title.size = 1,
           legend.text.size = 0.6,
           #legend.title.color = "black",
           #legend.text.color = "black",
            fontfamily = "ITC Officina Sans LT Book",
            legend.title.fontfamily = "ITC Officina Sans LT Bold") +
  tm_credits("Data till 26 Apr\nwww.fishwongy.com", position=c("left", "bottom"))
```
