```{r}
library(tidyverse)
library(tidycovid19)
library(paletteer)
library(ggplot2)
library(delabj)
library(patchwork)
library(socviz)
library(tsibble)
library(feasts)
library(timeDate)
library(lubridate)
library(here)
library(janitor)
library(ggrepel)
library(ggtext)
```

#Some functions for later use
```{r}
is_max <- function(x) {
  seq_along(x) == which.max(x)
}

my_colors <- function(palette="cb"){
### The palette with black:
  cb.palette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
  ## Same one Reversed
  rcb.palette <- rev(cb.palette)
  ## Blue and yellow first choices
  bly.palette <- c("#E69F00", "#0072B2", "#000000", "#56B4E9", "#009E73", "#F0E442", "#D55E00", "#CC79A7")
  if (palette=="cb") return(cb.palette) else if (palette=="rcb") return(rcb.palette) else if (palette=="bly") return(bly.palette) else stop("Choose cb, rcb, or bly ony.")
}



coalesce_join <- function(x, y, 
                          by = NULL, suffix = c(".x", ".y"), 
                          join = dplyr::full_join, ...) {
    joined <- join(x, y, by = by, suffix = suffix, ...)
    # names of desired output
    cols <- dplyr::union(names(x), names(y))
    
    to_coalesce <- names(joined)[!names(joined) %in% cols]
    suffix_used <- suffix[ifelse(endsWith(to_coalesce, suffix[1]), 1, 2)]
    # remove suffixes and deduplicate
    to_coalesce <- unique(substr(
        to_coalesce, 
        1, 
        nchar(to_coalesce) - nchar(suffix_used)
    ))
    
    coalesced <- purrr::map_dfc(to_coalesce, ~dplyr::coalesce(
        joined[[paste0(.x, suffix[1])]], 
        joined[[paste0(.x, suffix[2])]]
    ))
    names(coalesced) <- to_coalesce
    
    dplyr::bind_cols(joined, coalesced)[cols]
}

```

```{r}
covid_raw <- suppressWarnings(read_csv("~/COVID-19-geographic-disbtribution-worldwide-2020-05-03.csv", na = "NULL"))
```

```{r}
covid <- covid_raw %>%
  mutate(date = lubridate::dmy(dateRep)) %>% 
  filter(cases != -9)

colnames(covid)[7] <- "countries_and_territories"
colnames(covid)[8] <- "geo_id"
```


```{r}
df <- covid %>% select(5,6,7,12)
```


```{r}
dea <- aggregate(df$deaths, list(df$date), sum)
colnames(dea) <- c("date", "deaths")
con <- aggregate(df$cases, list(df$date), sum)
colnames(con) <- c("date", "confirmed")


df <- bind_cols(dea, con[2])
```

```{r}
df <- df %>% 
  mutate(weekend = isWeekend(date),
         holiday = isHoliday(as.timeDate(date), listHolidays())) %>%
  mutate(max_day = ifelse(is_max(deaths), date, NA),
         max_day = as_date(max_day))
```

```{r}
df_long <- gather(df, key = "mode", value = "index", "deaths" : "confirmed")

df_long$mode[df_long$mode == "confirmed"] <- "New cases"
df_long$mode[df_long$mode == "deaths"] <- "New deaths"
```


```{r}
ww <- 
  df_long %>% 
  filter(date >= as.Date("2020-03-05")) %>%
 # mutate(mode = recode(mode, `confirmed` = "New cases",
  #                      `deaths` = "New deaths")) %>%

ggplot(df_long, mapping = aes(x = date, y = index,
                                      group = mode, color = mode)) +
geom_vline(data = subset(df_long, weekend == TRUE),
             mapping = aes(xintercept = date),
             color = my_colors("bly")[5], size = 3, alpha = 0.1) +
  geom_line(size = 1.1) +
#  geom_text_repel(aes(label = format(max_day, format = "%a %b %d")),
 #                 size = rel(2), nudge_x = 1, show.legend = FALSE) +
  scale_color_manual(name = "", values = c("New cases" = "#83B692", "New deaths" = "#721121")) +
   facet_wrap(~mode, nrow = 1, scales = "free") +
  theme_delabj() +
labs(x = "", y = "",
       color = "Mode",
       title = "Daily new COVID-19 <b, style = 'color:#83B692'>cases</b> & <b, style = 'color:#721121'>deaths</b>",
       subtitle = "Global scale",
       caption = "") +
  theme(legend.position = "top",
        text = element_text(size = 12, family="ITC Officina Sans LT Book"),
        legend.text = element_text(size = 14),
       plot.title.position = "plot",
          plot.title = element_markdown(size = 21, family="ITC Officina Sans LT Bold"),
          plot.subtitle = element_text(size = 15),
          plot.caption = element_text(hjust = 0, size = rel(1)),
          # turn off the strip label and tighten the panel spacing
          strip.text = element_blank(),
          axis.text.x = element_text(size=12),
          axis.text.y = element_text(size=12),
       panel.grid.major = element_blank(),
       panel.grid.minor = element_blank(),
          panel.spacing.x = unit(-0.05, "lines"),
          panel.spacing.y = unit(0.3, "lines"),
          axis.title.x = element_text(size = 10),
          axis.title.y = element_text(size = 10))

```





**For USA**
```{r}
urlfile="https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv"

nytdata <- read_csv(url(urlfile))

write.csv(nytdata, file = "nytdata.csv", row.names = FALSE)
```

```{python}
import csv

with open('nytdata.csv') as f:
    reader = csv.DictReader(f)
    lines = [line for line in reader]

for prev_day, day in zip(lines, lines[1:]):
    day['new_cases'] = int(day['cases']) - int(prev_day['cases'])
    day['new_deaths'] = int(day['deaths']) - int(prev_day['deaths'])

import datetime

for line in lines:
    line['day'] = datetime.datetime.strptime(line['date'],
                                             '%Y-%m-%d').strftime('%A')

with open('data.csv', 'w') as f:
    writer = csv.DictWriter(f, lines[1].keys())
    writer.writeheader()
    writer.writerows(lines[1:])
```

    
```{r}
nytdata <- suppressWarnings(read_csv(
  "data.csv", na = "NULL"))
```


```{r}
nytdf <- nytdata %>% 
  mutate( weekend = isWeekend(date),
         holiday = isHoliday(as.timeDate(date), listHolidays())) %>%
  mutate(max_day = ifelse(is_max(deaths), date, NA),
         max_day = as_date(max_day))
```

```{r}
nyt_long <- gather(nytdf, key = "mode", value = "index", "new_cases" : "new_deaths")

nyt_long$mode[nyt_long$mode == "new_cases"] <- "New cases"
nyt_long$mode[nyt_long$mode == "new_deaths"] <- "New deaths"
```

```{r}
usa <- 
  nyt_long %>% 
  filter(date >= as.Date("2020-03-05")) %>%
ggplot(nyt_long, mapping = aes(x = date, y = index,
                                      group = mode, color = mode)) +
geom_vline(data = subset(nyt_long, weekend == TRUE),
             mapping = aes(xintercept = date),
             color = my_colors("bly")[5], size = 3, alpha = 0.1) +
  geom_line(size = 1.1) +
 # geom_text_repel(aes(label = format(max_day, format = "%a %b %d")),
  #                size = rel(2), nudge_x = 1, show.legend = FALSE) +
  #scale_color_delabj(name = "") +
  scale_color_manual(name = "", values = c("New cases" = "#83B692", "New deaths" = "#721121")) +
  #scale_y_log10() +
  theme_delabj() +
  facet_wrap(~mode, nrow = 1, scales = "free") +
labs(x = "", y = "",
       color = "Mode",
       title = "Daily new CVID-19 <b, style = 'color:#83B692'>cases</b> & <b, style = 'color:#721121'>deaths</b>",
       subtitle = "USA focus", #Data till 6 Apr
       caption = "Source: NYTimes; ECDC\nwww.fishwongy.com") +
  theme(legend.position = "top",
        text = element_text(size = 12, family="ITC Officina Sans LT Book"),
       plot.title.position = "plot",
          plot.title = element_markdown(size = 21, family="ITC Officina Sans LT Bold"),
          plot.subtitle = element_text(size = 15),
          plot.caption = element_text(hjust = 0, size = 15),
          plot.caption.position = "plot",
          # turn off the strip label and tighten the panel spacing
          strip.text = element_blank(),
          axis.text.x = element_text(size=12),
          axis.text.y = element_text(size=12),
       panel.grid.major = element_blank(),
       panel.grid.minor = element_blank(),
          panel.spacing.x = unit(-0.05, "lines"),
          panel.spacing.y = unit(0.3, "lines"),
          axis.title.x = element_text(size = 10),
          axis.title.y = element_text(size = 10),
          legend.text = element_text(size = 14))

```



```{r}
ww / usa +
   ggsave("WkendDea_patch.png", dpi = 320, width = 10.8, height = 12)
```






**For Weekday**
```{r}
df$day <- weekdays(as.Date(df$date))

df_dea <- aggregate(df$deaths, list(df$day), sum)
colnames(df_dea) <- c("day", "Deaths")

df_con <- aggregate(df$confirmed, list(df$day), sum)
colnames(df_con) <- c("day", "Confirmed")
df_wk <- bind_cols(df_dea, df_con[2])
df_wk <- gather(df_wk, key = "metric", value = "count", "Deaths" : "Confirmed")
  
  
df_wk$per_cent <- df_wk$count/ sum(df_wk$count) *100
df_wk$day <- as.factor(df_wk$day)
df_wk$day <- factor(df_wk$day,levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))
```

```{r}
glo_wk <- 
  df_wk %>%
ggplot(aes(x = day, y = count, fill = metric)) +
  geom_bar(stat = 'identity') +
  #geom_bar(group = 1, stat = "identity", fill = "#83B692") + 
  #geom_density(size = 1, color = "#FF6666") +
  theme_delabj() +
  scale_fill_manual(name = "", values = c("Confirmed" = "#83B692", "Deaths" = "#721121")) +
  facet_wrap(~metric, scales = "free", nrow = 1) +
  labs(x = "", y = "",
       #color = "Mode",
       title = "Cumulated <b, style = 'color:#83B692'>cases</b> & <b, style = 'color:#721121'>deaths</b> on each weekday",
       subtitle = "Global scale", #Data till 6 Apr
       caption = "") + #Source: NYTimes\nwww.fishwongy.com
  theme(legend.position = "top",
        text = element_text(size = 12, family="ITC Officina Sans LT Book"),
       plot.title.position = "plot",
          plot.title = element_markdown(size = 21, family="ITC Officina Sans LT Bold"),
          plot.subtitle = element_text(size = 15),
          plot.caption = element_text(hjust = 0, size = 15),
          plot.caption.position = "plot",
          # turn off the strip label and tighten the panel spacing
          strip.text = element_blank(),
          axis.text.x = element_text(size=12),
          axis.text.y = element_text(size=12),
       panel.grid.major = element_blank(),
       panel.grid.minor = element_blank(),
          panel.spacing.x = unit(-0.05, "lines"),
          panel.spacing.y = unit(0.3, "lines"),
          axis.title.x = element_text(size = 10),
          axis.title.y = element_text(size = 10),
          legend.text = element_text(size = 14))
```




```{r}
nytdata$count <- 1
nyt_dea <- aggregate(nytdata$deaths, list(nytdata$day), sum)
colnames(nyt_dea) <- c("day", "Deaths")

nyt_con <- aggregate(nytdata$cases, list(nytdata$day), sum)
colnames(nyt_con) <- c("day", "Confirmed") 
nyt_wk <- bind_cols(nyt_dea, nyt_con[2])
nyt_wk <- gather(nyt_wk, key = "metric", value = "count", "Deaths" : "Confirmed")
  
nyt_wk$per_cent <- nyt_wk$count/ sum(nyt_wk$count) *100
nyt_wk$day <- as.factor(nyt_wk$day)
nyt_wk$day <- factor(nyt_wk$day,levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))
```

```{r}
usa_wk <- 
  nyt_wk %>%
ggplot(aes(x = day, y = count, fill = metric)) +
  geom_bar(stat = 'identity') +
  #geom_bar(group = 1, stat = "identity", fill = "#83B692") + 
  #geom_density(size = 1, color = "#FF6666") +
  theme_delabj() +
  #scale_fill_delabj(name = "", breaks = c("Deaths", "Confirmed")) +
  scale_fill_manual(name = "", values = c("Confirmed" = "#83B692", "Deaths" = "#721121")) +
  facet_wrap(~metric, scales = "free", nrow = 1) +
  labs(x = "", y = "",
       #color = "Mode",
       title = "Cumulated <b, style = 'color:#83B692'>cases</b> & <b, style = 'color:#721121'>deaths</b> on each weekday",
       subtitle = "USA focus", #Data till 6 Apr
       caption = "Source: NYTimes; ECDC\nwww.fishwongy.com") + #Source: NYTimes; ECDC\nwww.fishwongy.com
  theme(legend.position = "top",
        text = element_text(size = 12, family="ITC Officina Sans LT Book"),
       plot.title.position = "plot",
          plot.title = element_markdown(size = 21, family="ITC Officina Sans LT Bold"),
          plot.subtitle = element_text(size = 15),
          plot.caption = element_text(hjust = 0, size = 15),
          plot.caption.position = "plot",
          # turn off the strip label and tighten the panel spacing
          strip.text = element_blank(),
          axis.text.x = element_text(size=12),
          axis.text.y = element_text(size=12),
       panel.grid.major = element_blank(),
       panel.grid.minor = element_blank(),
          panel.spacing.x = unit(-0.05, "lines"),
          panel.spacing.y = unit(0.3, "lines"),
          axis.title.x = element_text(size = 10),
          axis.title.y = element_text(size = 10),
          legend.text = element_text(size = 14))
```


```{r}
(glo_wk / usa_wk) +
   ggsave("WkDea_patch2.png", dpi = 320, width = 11.8, height = 12)
```







#Adding Active cases & Daily confirm (world-wide/ USA)
```{r}
merged <- download_merged_data(cached = TRUE, silent = TRUE)
merged <- merged %>% select(1:6)
merged$active <- merged$confirmed - merged$recovered
```

```{r}
merged %>% 
  filter(date >= as.Date("2020-02-01")) %>%
   filter(country %in% c("Italy", "Germany", "France", "Portugal", "US", "United Kingdom", "Spain", "Netherlands", "Korea, South")) %>%
  mutate(end_label = ifelse(date == max(date) - 1, country, NA),
         country = recode(country, `United Kingdom` = "UK",
                          `Korea, South` = "Korea")) %>%
 # mutate(mode = recode(mode, `confirmed` = "New cases",
  #                      `deaths` = "New deaths")) %>%

ggplot(aes(x = date, y = active, label = end_label)) +
  geom_line(size = 1.1, color = "#83B692") +
  #geom_text(nudge_x = -6.5,
   #               nudge_y = -5020.4,
                  #segment.color = NA,
    #              color = "#721121",
     #             size = 5,
      #            family="ITC Officina Sans LT Bold") + 
  theme_delabj() +
  scale_y_continuous(position = "right") +
  facet_wrap(~country, scales = "free", nrow = 3) +
labs(x = "", y = "",
     title = "'We are past the peak'\n",  
     #title = "Daily new COVID-19 <b, style = 'color:#83B692'>cases</b> & <b, style = 'color:#721121'>deaths</b>",
       subtitle = "<b, style = 'color:#83B692'>**Active cases**</b> over time\n",
       caption = "Source: NYTimes; ECDC\nwww.fishwongy.com") +
  theme(legend.position = "top",
        text = element_text(size = 12, family="ITC Officina Sans LT Book"),
        legend.text = element_text(size = 14),
       plot.title.position = "plot",
        plot.title = element_markdown(size = 26, family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_markdown(size = 20),
        plot.caption = element_text(size = 16),
        plot.caption.position = "plot", 
          # turn off the strip label and tighten the panel spacing
        strip.text = element_text(family = "ITC Officina Sans LT Bold", size = 18, color = "#721121"),
          axis.text.x = element_text(size=12, family="ITC Officina Sans LT Bold"),
          axis.text.y = element_text(size=13, family = "ITC Officina Sans LT Bold"),
       panel.background = element_blank(),
       #panel.grid.major.x = element_blank(),
       panel.grid.minor = element_blank(),
          panel.spacing.x = unit(-0.05, "lines"),
          panel.spacing.y = unit(0.3, "lines"),
          axis.title.x = element_text(size = 10),
          axis.title.y = element_text(size = 10)) +
   ggsave("~/peak.png", dpi = 320, width = 12.8, height = 12)
```

#Daily confirm cases (Area graph), covid is from the prev Rmd w/ ECDC data
```{r}
covid2 <- covid %>% select(5,6,7,12)
colnames(covid2)[3] <- "country"
```
```{r}
covid2 %>% 
  filter(date >= as.Date("2020-02-15") & cases >= 0) %>%
  mutate(country = recode(country, `United_Kingdom` = "UK",
                        `United_States_of_America` = "USA",
                        `South_Korea` = "Korea")) %>%
  filter(country %in% c("Italy", "Germany", "France", "Portugal", "USA", "UK", "Spain", "Netherlands", "Korea")) %>%
  mutate(end_label = ifelse(date == max(date) - 2, country, NA),
         end_label = recode(end_label, `United Kingdom` = "UK")) %>%


ggplot(aes(x = date, y = cases, label = end_label)) +
  geom_bar(stat = "identity", width = 1, fill = "#83B692") +
 # geom_text(nudge_x = -10.5,
  #          nudge_y = 1020.4,
                  #segment.color = NA,
   #               color = "#721121",
    #              size = 6,
     #             family="ITC Officina Sans LT Bold") + 
  theme_delabj() +
  scale_y_continuous(position = "right") +
  facet_wrap(~country, scales = "free", nrow = 3) +
labs(x = "", y = "",
     title = "'We are past the peak'\n",  
     #title = "Daily new COVID-19 <b, style = 'color:#83B692'>cases</b> & <b, style = 'color:#721121'>deaths</b>",
       subtitle = "<b, style = 'color:#83B692'>**Daily confirmed cases**</b> over time\n",
       caption = "Source: NYTimes; ECDC\nwww.fishwongy.com") +
  theme(legend.position = "top",
        text = element_text(size = 12, family="ITC Officina Sans LT Book"),
        legend.text = element_text(size = 14),
       plot.title.position = "plot",
        plot.title = element_markdown(size = 26, family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_markdown(size = 20),
        plot.caption = element_text(size = 16),
        plot.caption.position = "plot", 
          # turn off the strip label and tighten the panel spacing
        strip.text = element_text(family = "ITC Officina Sans LT Bold", size = 18, color = "#721121"),
        axis.text.x = element_text(size=12, family="ITC Officina Sans LT Bold"),
        axis.text.y = element_text(size=14, family="ITC Officina Sans LT Bold"),
       panel.background = element_blank(),
       #panel.grid.major.x = element_blank(),
       panel.grid.minor = element_blank(),
          panel.spacing.x = unit(-0.05, "lines"),
          panel.spacing.y = unit(0.3, "lines"),
          axis.title.x = element_text(size = 10),
          axis.title.y = element_text(size = 10)) +
   ggsave("~/confirm.png", dpi = 320, width = 12.8, height = 14)
```

#US states daily confirm case
```{r}
urlfile="https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv"

nytdata <- read_csv(url(urlfile))

write.csv(nytdata, file = "/Volumes/My Passport for Mac/R/convid-19/15 May 20/nytimes/nytdata.csv", row.names = FALSE)
```

```{python}
import csv

with open('~/nytdata.csv') as f:
    reader = csv.DictReader(f)
    lines = [line for line in reader]

for prev_day, day in zip(lines, lines[1:]):
    day['new_cases'] = int(day['cases']) - int(prev_day['cases'])
    day['new_deaths'] = int(day['deaths']) - int(prev_day['deaths'])

import datetime

for line in lines:
    line['day'] = datetime.datetime.strptime(line['date'],
                                             '%Y-%m-%d').strftime('%A')

with open(~/data.csv', 'w') as f:
    writer = csv.DictWriter(f, lines[1].keys())
    writer.writeheader()
    writer.writerows(lines[1:])
```

```{r}
nytdata <- suppressWarnings(read_csv(
  "~/data.csv", na = "NULL"))
```

#US state daily confirm case
```{r}
nytdata %>% 
  filter(date >= as.Date("2020-02-15") & new_cases >= 31) %>%
ggplot(aes(x = date, y = new_cases)) +
  geom_bar(stat = "identity", width = 1, fill = "#83B692") +
 # geom_text(nudge_x = -10.5,
  #          nudge_y = 1020.4,
                  #segment.color = NA,
   #               color = "#721121",
    #              size = 6,
        #             family="ITC Officina Sans LT Bold") + 
  theme_delabj() +
  scale_y_continuous(position = "right") +
  facet_wrap(~state, scales = "free", nrow = 6) +
labs(x = "", y = "",
     title = "<b, style = 'color:#83B692'>**Daily confirmed cases**</b> over time\n",  
     #title = "Daily new COVID-19 <b, style = 'color:#83B692'>cases</b> & <b, style = 'color:#721121'>deaths</b>",
       subtitle = "Top 30 <b, style = 'color:#721121'>US state</b>",
       caption = "Source: NYTimes\nwww.fishwongy.com") +
  theme(legend.position = "top",
        text = element_text(size = 12, family="ITC Officina Sans LT Book"),
        legend.text = element_text(size = 14),
       plot.title.position = "plot",
        plot.title = element_markdown(size = 30, family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_markdown(size = 23),
        plot.caption = element_text(size = 16),
        plot.caption.position = "plot", 
          # turn off the strip label and tighten the panel spacing
        strip.text = element_text(family = "ITC Officina Sans LT Bold", size = 18, color = "#721121"),
        axis.text.x = element_text(size=12, family="ITC Officina Sans LT Bold"),
        axis.text.y = element_text(size=14, family="ITC Officina Sans LT Bold"),
       panel.background = element_blank(),
       #panel.grid.major.x = element_blank(),
       panel.grid.minor = element_blank(),
          panel.spacing.x = unit(-0.05, "lines"),
          panel.spacing.y = unit(0.3, "lines"),
          axis.title.x = element_text(size = 10),
          axis.title.y = element_text(size = 10)) +
   ggsave("~/us_state.png", dpi = 320, width = 18.8, height = 18)
```











#Aggregate global by dplyr
```{r}
#glo_act <- 
  merged %>% 
  filter(date >= as.Date("2020-02-01")) %>%
  group_by(date) %>%
  summarise(sum_active = sum(active)) %>%   #Gpby + summarise = aggre
  ungroup() %>%
  mutate(end_label = ifelse(date == max(date) - 1, "Global", NA)) %>%
 # mutate(mode = recode(mode, `confirmed` = "New cases",
  #                      `deaths` = "New deaths")) %>%

ggplot(aes(x = date, y = sum_active, label = end_label)) +
  geom_line(size = 1.1, color = "#83B692") +
  geom_text_repel(nudge_x = -1.1,
                  nudge_y = -520.4,
                  #segment.color = NA,
                  color = "#721121",
                  size = 3,
                  family="ITC Officina Sans LT Bold") + 
  theme_delabj() +
 # facet_wrap(~country, scales = "free", nrow = 2) +
labs(x = "", y = "",
     title = "'We are past the peaek'",  
     #title = "Daily new COVID-19 <b, style = 'color:#83B692'>cases</b> & <b, style = 'color:#721121'>deaths</b>",
       subtitle = "<b, style = 'color:#83B692'>Active cases</b> over time\n",
       caption = "") +
  theme(legend.position = "top",
        text = element_text(size = 12, family="ITC Officina Sans LT Book"),
        legend.text = element_text(size = 14),
       plot.title.position = "plot",
          plot.title = element_markdown(size = 21, family="ITC Officina Sans LT Bold"),
          plot.subtitle = element_markdown(size = 15),
          plot.caption = element_text(hjust = 0, size = rel(1)),
          # turn off the strip label and tighten the panel spacing
          strip.text = element_blank(),
          axis.text.x = element_text(size=12),
          axis.text.y = element_text(size=12),
       panel.grid.major = element_blank(),
       panel.grid.minor = element_blank(),
          panel.spacing.x = unit(-0.05, "lines"),
          panel.spacing.y = unit(0.3, "lines"),
          axis.title.x = element_text(size = 10),
          axis.title.y = element_text(size = 10))
```
